USE cs3200_project_1;

INSERT INTO Job (JobID, Company, Title, UserID) VALUES
('job_001', 'Google', 'Software Engineer', '1'),
('job_002', 'Amazon', 'Data Scientist', '2'),
('job_003', 'Microsoft', 'Product Manager', '3'),
('job_004', 'Meta', 'UX Designer', '4'),
('job_005', 'Apple', 'iOS Developer', '5'),
('job_006', 'Netflix', 'DevOps Engineer', '6'),
('job_007', 'Tesla', 'ML Engineer', '7'),
('job_008', 'Spotify', 'Backend Developer', '8'),
('job_009', 'Adobe', 'Frontend Developer', '9'),
('job_010', 'Salesforce', 'Full Stack Developer', '10'),
('job_011', 'IBM', 'Cloud Architect', '11'),
('job_012', 'Oracle', 'Database Administrator', '12'),
('job_013', 'Uber', 'Senior Software Engineer', '13'),
('job_014', 'Airbnb', 'Platform Engineer', '14'),
('job_015', 'LinkedIn', 'Data Engineer', '15'),
('job_016', 'Twitter', 'Security Engineer', '16'),
('job_017', 'Snap', 'Mobile Developer', '17'),
('job_018', 'Stripe', 'API Developer', '18'),
('job_019', 'Shopify', 'E-commerce Developer', '19'),
('job_020', 'Square', 'Payment Systems Engineer', '20'),
('job_021', 'Coinbase', 'Blockchain Developer', '21'),
('job_022', 'Robinhood', 'Quantitative Developer', '22'),
('job_023', 'Zoom', 'Video Engineer', '23'),
('job_024', 'Slack', 'Infrastructure Engineer', '24'),
('job_025', 'Dropbox', 'Storage Engineer', '25'),
('job_026', 'Atlassian', 'Site Reliability Engineer', '26'),
('job_027', 'GitHub', 'Developer Advocate', '27'),
('job_028', 'GitLab', 'Backend Engineer', '28'),
('job_029', 'Redis', 'Systems Engineer', '29'),
('job_030', 'MongoDB', 'Database Engineer', '30'),
('job_031', 'Elastic', 'Search Engineer', '31'),
('job_032', 'Databricks', 'Data Platform Engineer', '32'),
('job_033', 'Snowflake', 'Analytics Engineer', '33'),
('job_034', 'Palantir', 'Forward Deployed Engineer', '34'),
('job_035', 'Twilio', 'Communications Engineer', '35'),
('job_036', 'SendGrid', 'Email Platform Engineer', '36'),
('job_037', 'Mailchimp', 'Marketing Engineer', '37'),
('job_038', 'HubSpot', 'Growth Engineer', '38'),
('job_039', 'Zendesk', 'Customer Support Engineer', '39'),
('job_040', 'ServiceNow', 'Enterprise Developer', '40'),
('job_041', 'Workday', 'HR Systems Engineer', '41'),
('job_042', 'SAP', 'ERP Developer', '42'),
('job_043', 'Cisco', 'Network Engineer', '43'),
('job_044', 'VMware', 'Virtualization Engineer', '44'),
('job_045', 'Dell', 'Systems Software Engineer', '45'),
('job_046', 'HP', 'Hardware Engineer', '46'),
('job_047', 'Intel', 'Chip Design Engineer', '47'),
('job_048', 'NVIDIA', 'GPU Software Engineer', '48'),
('job_049', 'AMD', 'Graphics Engineer', '49'),
('job_050', 'Qualcomm', 'Embedded Systems Engineer', '50');