USE cs3200_project_1;

INSERT INTO Education (EduID, Institution, Grade, Credential, UserID) VALUES
('edu_sarah_001', 'Northeastern University', 93, 'Bachelor of Science in Computer Science, Class of 2024, GPA 3.7/4.0, Dean''s List, Capstone: ML Recommendation System', '1'),
('edu_mark_001', 'University of California Berkeley', 88, 'Bachelor of Science in Computer Science, Class of 2018, Focus on Distributed Systems and Algorithms', '2'),
('edu_mark_002', 'Stanford University', 90, 'Master of Science in Computer Science, 2019, Specialization in Systems and Networking', '2'),
('edu_001', 'MIT', 92, 'Bachelor of Science in Computer Science, 2021, GPA 3.8/4.0, Research in AI', '3'),
('edu_002', 'Carnegie Mellon University', 89, 'Bachelor of Science in Software Engineering, 2020, Minor in Human-Computer Interaction', '4'),
('edu_003', 'Stanford University', 95, 'PhD in Artificial Intelligence, 2021, Dissertation on Natural Language Processing', '5'),
('edu_004', 'University of Washington', 85, 'Bachelor of Science in Computer Science, 2022, Web Development Focus', '6'),
('edu_005', 'Columbia University', 91, 'Master of Science in Data Science, 2021, Specialization in Machine Learning', '7'),
('edu_006', 'Georgia Tech', 87, 'Bachelor of Science in Computer Science, 2020, Cloud Computing Specialization', '8'),
('edu_007', 'University of Michigan', 88, 'Bachelor of Business Administration, 2021, Minor in Computer Science', '9'),
('edu_008', 'UC San Diego', 86, 'Bachelor of Science in Computer Engineering, 2019, Systems Focus', '10'),
('edu_009', 'University of Texas Austin', 90, 'Bachelor of Science in Computer Science, 2021, Mobile Development Track', '11'),
('edu_010', 'Purdue University', 84, 'Bachelor of Science in Cybersecurity, 2020, CISSP Certified', '12'),
('edu_011', 'General Assembly', 82, 'UX Design Bootcamp, 2022, 12-week intensive program', '13'),
('edu_012', 'University of Illinois', 89, 'Master of Science in Cloud Computing, 2018, AWS Specialization', '14'),
('edu_013', 'Arizona State University', 85, 'Bachelor of Science in Software Engineering, 2021, Agile Development', '15'),
('edu_014', 'New York University', 87, 'Bachelor of Science in Computer Science, 2022, Blockchain Focus', '16'),
('edu_015', 'Boston University', 91, 'MBA, 2020, Technology Management Concentration', '17'),
('edu_016', 'University of Florida', 83, 'Bachelor of Science in Electrical Engineering, 2019, Embedded Systems', '18'),
('edu_017', 'UC Berkeley', 88, 'Bachelor of Arts in Data Science, 2021, Growth Analytics Focus', '19'),
('edu_018', 'Penn State', 86, 'Bachelor of Science in Information Technology, 2020, Network Administration', '20'),
('edu_019', 'Caltech', 94, 'PhD in Computer Science, 2020, AI Research Focus', '21'),
('edu_020', 'Cornell University', 89, 'Bachelor of Science in Computer Science, 2020, Systems Programming', '22'),
('edu_021', 'App Academy', 80, 'Full-Stack Web Development Bootcamp, 2022, JavaScript Specialization', '23'),
('edu_022', 'University of Maryland', 87, 'Bachelor of Science in Computer Science, 2018, Database Systems', '24'),
('edu_023', 'Rice University', 91, 'Bachelor of Science in Computer Science, 2017, Distributed Systems', '25'),
('edu_024', 'USC', 85, 'Bachelor of Science in Computer Science, 2021, Game Development', '26'),
('edu_025', 'Northwestern University', 88, 'Bachelor of Arts in Technical Communication, 2020, CS Minor', '27'),
('edu_026', 'Duke University', 90, 'Bachelor of Science in Computer Science, 2019, Enterprise Software', '28'),
('edu_027', 'MIT', 95, 'PhD in Robotics, 2021, Computer Vision and Autonomous Systems', '29'),
('edu_028', 'UC Berkeley', 92, 'Bachelor of Science in Computer Science, 2018, Compilers and Programming Languages', '30'),
('edu_029', 'University of Southern California', 86, 'Bachelor of Science in Computer Science, 2021, Multimedia Systems', '31'),
('edu_030', 'Princeton University', 93, 'Bachelor of Science in Computer Science, 2020, Quantitative Finance', '32'),
('edu_031', 'University of Pennsylvania', 87, 'Bachelor of Science in Computer Science, 2021, E-commerce Systems', '33'),
('edu_032', 'Georgia Tech', 89, 'Master of Science in Computer Science, 2019, Audio Signal Processing', '34'),
('edu_033', 'Columbia University', 91, 'Master of Science in Computational Linguistics, 2020, NLP Focus', '35'),
('edu_034', 'University of Washington', 88, 'Bachelor of Science in Computer Science, 2019, Information Retrieval', '36'),
('edu_035', 'UC Santa Barbara', 85, 'Bachelor of Science in Computer Engineering, 2021, Performance Engineering', '37'),
('edu_036', 'Virginia Tech', 84, 'Bachelor of Science in Computer Science, 2020, Software Testing', '38'),
('edu_037', 'University of Colorado Boulder', 86, 'Bachelor of Science in Computer Science, 2021, Accessibility Technologies', '39'),
('edu_038', 'UC Irvine', 87, 'Bachelor of Science in Computer Science, 2020, Distributed Systems', '40'),
('edu_039', 'Harvard University', 93, 'Bachelor of Science in Computer Science, 2019, Developer Tools', '41'),
('edu_040', 'MIT', 94, 'Master of Science in Robotics, 2020, Autonomous Vehicles', '42'),
('edu_041', 'Carnegie Mellon', 92, 'Master of Science in Computer Vision, 2021, Deep Learning', '43'),
('edu_042', 'UC Berkeley', 88, 'Bachelor of Science in Electrical Engineering, 2018, Network Engineering', '44'),
('edu_043', 'Brown University', 89, 'Bachelor of Science in Computer Science, 2020, API Design', '45'),
('edu_044', 'Stanford University', 95, 'Master of Science in Cryptography, 2019, Security Systems', '46'),
('edu_045', 'University of Michigan', 87, 'Bachelor of Science in Computer Science, 2020, Financial Technology', '47'),
('edu_046', 'University of Toronto', 90, 'Bachelor of Science in Computer Engineering, 2019, Reliability Engineering', '48'),
('edu_047', 'UC Berkeley', 92, 'Bachelor of Science in Electrical Engineering, 2018, Hardware Design', '49'),
('edu_048', 'Purdue University', 85, 'Bachelor of Science in Computer Engineering, 2021, IoT Systems', '50'),
('edu_049', 'University of Wisconsin', 88, 'Bachelor of Science in Computer Science, 2019, Distributed Storage', '51'),
('edu_050', 'Oregon State University', 91, 'Bachelor of Science in Computer Science, 2017, Linux Systems', '52'),
('edu_051', 'University of Chicago', 89, 'Bachelor of Science in Computer Science, 2020, Real-time Systems', '53'),
('edu_052', 'NC State', 86, 'Bachelor of Science in Computer Science, 2021, Cloud Native Technologies', '54'),
('edu_053', 'University of Minnesota', 87, 'Bachelor of Science in Data Science, 2020, Big Data Engineering', '55'),
('edu_054', 'Northeastern University', 84, 'Bachelor of Science in Computer Science, 2022, Co-op Program', '56'),
('edu_055', 'Boston College', 88, 'Bachelor of Science in Computer Science, 2021, Software Architecture', '57');