USE cs3200_project_1;

INSERT INTO Output (InputID, OutputID, OutputData, Timestamp) VALUES
('input_sarah_001', 'output_sarah_001_1', 'Focus on quantifiable metrics, relevant tech stack (Python, Java, C++), and project scale. Use action verbs and emphasize scalability.', '09:15:45'),
('input_sarah_002', 'output_sarah_002_1', 'Key keywords: distributed systems, microservices, cloud infrastructure, ML/AI, system design, performance optimization, CI/CD.', '10:22:31'),
('input_sarah_003', 'output_sarah_003_1', 'Structure as: "Developed ML recommendation engine achieving X% accuracy. Processed Y million data points using Python/TensorFlow."', '14:35:58'),
('input_sarah_004', 'output_sarah_004_1', 'Quantify with percentages, time saved, users impacted, revenue generated. Example: "Implemented 5 features increasing engagement by 23%."', '16:49:12'),
('input_sarah_005', 'output_sarah_005_1', 'Boston new grad salaries: $110K-$140K base. FAANG offers $130K-$140K plus $30K-$50K signing bonus. Total comp $180K-$220K first year.', '11:20:33'),
('input_mark_001', 'output_mark_001_1', 'Use neutral language: "Impacted by company restructuring in 2024." Focus on achievements during tenure. Keep brief and pivot to future goals.', '08:30:38'),
('input_mark_002', 'output_mark_002_1', 'Emphasize scale (2B+ users), leadership (mentored 5 engineers), technical depth (35% latency reduction), cross-functional impact.', '09:45:34'),
('input_mark_003', 'output_mark_003_1', 'Focus on 5-7 most relevant applications. Group by tier and tailor to each company tech stack. Show strategic targeting not desperation.', '13:22:56'),
('input_mark_004', 'output_mark_004_1', 'Include team size, projects delivered, hiring contributions, code review volume. Quantify impact on velocity and reliability.', '15:10:49'),
('input_mark_005', 'output_mark_005_1', 'Keywords: microservices, Kafka, distributed tracing, service mesh, Kubernetes, high availability, circuit breakers, eventual consistency.', '10:15:43'),
('input_mark_006', 'output_mark_006_1', 'FAANG version: emphasize scale and infrastructure. Startup version: highlight versatility and speed. Adjust emphasis per company culture.', '14:55:36'),
('input_001', 'output_001_1', 'Summary format: experience level + key skills + achievements + target role. Keep 2-3 sentences total.', '09:40:42'),
('input_002', 'output_002_1', 'Action verbs: architected, optimized, scaled, deployed, automated, migrated. Use with metrics: "Optimized queries reducing latency by 60%."', '11:15:49'),
('input_003', 'output_003_1', 'Focus on practical applications and business value. Emphasize production deployment, scalability, measurable impact over theory.', '10:06:02'),
('input_004', 'output_004_1', 'Emphasize React, TypeScript, design systems, accessibility, performance optimization. Highlight: "Built design system used by 20+ engineers."', '13:30:39'),
('input_005', 'output_005_1', 'Connect analysis to business outcomes: revenue increase, cost savings, efficiency gains. Use specific dollar amounts and percentages.', '15:20:34'),
('input_006', 'output_006_1', 'Top certs: AWS Solutions Architect, CKA/CKAD, Terraform Associate. Show certification in action with hands-on achievements.', '08:45:56'),
('input_007', 'output_007_1', 'Emphasize strategic impact: "$10M ARR growth," cross-functional leadership, P&L ownership, team building. Show business acumen.', '12:11:13'),
('input_008', 'output_008_1', 'Key metrics: uptime (99.99%), MTTR, incident reduction, SLO achievement. Example: "Improved uptime from 99.5% to 99.95%, reducing incidents by 60%."', '14:25:35'),
('input_009', 'output_009_1', 'Include App Store links, download counts, ratings, video demos, GitHub repos. Quantify: "4.7★ rating, 50K+ downloads, $15K monthly revenue."', '09:56:01'),
('input_010', 'output_010_1', 'Top certs: CISSP, CEH, OSCP, Security+. Combine with practical achievements in penetration testing and compliance (SOC2, HIPAA).', '11:40:46'),
('input_011', 'output_011_1', 'Treat bootcamp projects as real work. Focus on complete lifecycle, real-world features, deployment, testing. Mention bootcamp briefly.', '10:30:33'),
('input_012', 'output_012_1', 'Include services migrated (numbers), cloud platform, cost savings, uptime improvements. Example: "Migrated 50+ services reducing costs by $400K annually."', '13:45:40'),
('input_013', 'output_013_1', 'Metrics: test coverage increased, manual testing time reduced, bugs caught pre-production. Quantify time saved and quality improvements.', '15:16:05'),
('input_014', 'output_014_1', 'Emphasize transferable skills: high-frequency trading, transaction processing at scale, security, real-time payment systems.', '08:20:51'),
('input_015', 'output_015_1', 'Bridge business + technical skills. Position for Technical PM, Engineering Manager roles. Highlight ROI analysis and P&L ownership.', '12:35:37'),
('input_016', 'output_016_1', 'Keywords: RTOS, AUTOSAR, ISO 26262, CAN bus, ADAS, safety-critical systems, firmware development. Focus on automotive standards.', '14:50:43'),
('input_017', 'output_017_1', 'Show revenue impact: "Growth engineering improved conversion by 25% generating $2M additional revenue." Connect technical work to business metrics.', '09:11:02'),
('input_018', 'output_018_1', 'Valuable certs: Cisco CCNA/CCNP, Juniper JNCIA. Highlight: "Managed network infrastructure supporting 10K+ endpoints with 99.9% uptime."', '11:25:58'),
('input_019', 'output_019_1', 'List publications but prioritize implementation: "Research published in NeurIPS - deployed model in production serving 1M users daily."', '10:45:32'),
('input_020', 'output_020_1', 'Startup achievements: "Built developer platform reducing deployment time from hours to minutes, adopted by 50+ engineers company-wide."', '13:20:45'),
('input_021', 'output_021_1', 'Create professional portfolio site. Include client testimonials, project case studies, tech stack details, live demos. Show breadth and depth.', '15:36:01'),
('input_022', 'output_022_1', 'Metrics: query response time reduced, index optimization, data volume processed. Example: "Optimized queries handling 10M records, reducing latency by 70%."', '08:50:39'),
('input_023', 'output_023_1', 'Frame leadership humbly: "Mentored junior engineers resulting in 3 promotions" vs "I''m an amazing leader." Let achievements speak for themselves.', '12:15:54'),
('input_024', 'output_024_1', 'Game dev metrics: player retention, MAU, frame rate optimization, memory usage. Example: "Optimized rendering achieving 60fps on low-end devices."', '14:40:36'),
('input_025', 'output_025_1', 'Show impact: "Created API documentation reducing developer onboarding time from 2 weeks to 3 days, improving developer satisfaction by 40%."', '09:31:12'),
('input_026', 'output_026_1', 'Solutions engineering metrics: deals closed, contract value, customer satisfaction scores, technical win rate. Connect demos to revenue.', '11:05:45'),
('input_027', 'output_027_1', 'For AV companies, emphasize: object detection accuracy, real-time processing, sensor fusion, safety validation. Include deployment scale.', '13:51:00'),
('input_028', 'output_028_1', 'Compiler metrics: compilation speed improvements, code size reduction, optimization passes. Example: "Reduced binary size by 30%."', '15:25:33'),
('input_029', 'output_029_1', 'Video metrics: bitrate optimization, latency reduction, CDN efficiency. Example: "Reduced streaming latency from 3s to 800ms serving 5M viewers."', '08:36:50'),
('input_030', 'output_030_1', 'Fintech keywords: low-latency systems, order execution, risk management, market data processing, regulatory compliance, trading algorithms.', '10:21:05'),
('input_031', 'output_031_1', 'E-commerce metrics: conversion rate lift, cart abandonment reduction, page load time. Connect technical work to revenue and user experience.', '12:45:40'),
('input_032', 'output_032_1', 'Audio metrics: latency, audio quality (bitrate/codec), processing efficiency. Example: "Implemented audio pipeline reducing latency by 50ms."', '14:10:54'),
('input_033', 'output_033_1', 'NLP metrics: model accuracy, inference time, training efficiency. Example: "Improved chatbot accuracy from 75% to 92% using BERT fine-tuning."', '09:25:37'),
('input_034', 'output_034_1', 'Search metrics: relevance score, query latency, index size. Example: "Optimized search indexing reducing query time from 500ms to 50ms."', '11:51:02'),
('input_035', 'output_035_1', 'Performance metrics: requests per second, response time, error rate under load. Quantify capacity improvements and system stability.', '13:15:45'),
('input_036', 'output_036_1', 'Test automation: coverage percentage, test execution time, CI/CD integration. Example: "Automated 85% of regression tests reducing cycle from 3 days to 4 hours."', '15:40:33'),
('input_037', 'output_037_1', 'Accessibility impact: WCAG compliance level, screen reader compatibility, keyboard navigation. Show user reach and legal compliance.', '08:56:00'),
('input_038', 'output_038_1', 'Observability: monitoring coverage, alert accuracy, MTTD. Example: "Implemented distributed tracing reducing incident diagnosis time by 75%."', '10:30:51'),
('input_039', 'output_039_1', 'Developer tools: adoption rate, time saved, developer satisfaction. Example: "Built CLI tool used by 100+ developers saving 5 hours/week each."', '12:55:37'),
('input_040', 'output_040_1', 'Robotics: path planning accuracy, sensor fusion latency, safety validation. Emphasize real-world testing and deployment at scale.', '14:20:46'),
('input_041', 'output_041_1', 'Computer vision: model accuracy, inference speed, dataset size. Example: "Achieved 95% object detection accuracy at 30fps on edge devices."', '09:45:55'),
('input_042', 'output_042_1', 'Network metrics: throughput, packet loss, latency, uptime. Example: "Optimized routing reducing latency by 25ms across 10K+ nodes."', '11:10:40'),
('input_043', 'output_043_1', 'API design: adoption rate, developer experience, performance. Example: "Designed GraphQL API reducing client queries by 60%, adopted by 50+ services."', '13:36:02');